#ifndef SHELL_ERROR_H
#define SHELL_ERROR_H

typedef enum
{
    ERR_NONE = 0,
    EXEC_WHERE_JOB,
    EXEC_EMPTY_ROOT,
    EXEC_EMPTY_JOB,
    EXEC_WHERE_CONVEYOR,
    EXEC_WRONG_CONVEYOR_CONNECT,
    EXEC_ERR_PID_LIST,
    EXEC_CANT_FORK,
    EXEC_EMPTY_CONVEYOR,
    EXEC_EMPTY_CMD,
    EXEC_EMPTY_PROCESS,
    EXEC_WRONG_PROCESS,
    EXEC_EMPTY_RE_DIR,
    EXEC_EMPTY_SUB_PROCESS,
    FILE_PERMISSION_DENIED,
    FILE_NOT_EXIST,
    FILE_SYSTEM_ERR,
    DUP_ERR,
    WRONG_OUTPUT_MODE,
    NOT_FIND_PID,
    EXEC_UNEXPECT_PID,
    EMPTY_INPUT,
    UNEXPECT_TOKEN
} error_t;

#endif //SHELL_ERROR_H
